=head1 NAME

linux-atm - preliminary manpage
aread
awrite
enitune
ilmid
saaldump
sonetdiag
ttcp_atm
zntune

=head1 DOCUMENTATION

atm-tools is a package containing the basic tools that are needed for
setting up, monitoring, and tuning ATM networks. All available
documentation can be found in /usr/share/doc/atm-tools in Debian
systems, and on the Web on: http://linux-atm.sourceforge.net.

=head1 BUGS

Many. Be prepared to debug.

=head1 AUTHOR

This manpage was written by Marc Haber for linux-atm packaging in
Debian/GNU Operating System.
