#!/bin/sh -e

upgrade_quirks() {
  [ "$2" ] || return 0

  dpkg --compare-versions $2 lt 1:2.5.1-1.3 || return 0

  # replaced by a symlink in 1:2.5.1-1.3, but dpkg fails to do it on upgrades
  if [ -d /usr/share/doc/br2684ctl -a ! -L /usr/share/doc/br2684ctl ] ; then
    rmdir /usr/share/doc/br2684ctl
    ln -s /usr/share/doc/libatm1 /usr/share/doc/br2684ctl
  fi

  return 0
}

case "$1" in
    configure)
    upgrade_quirks "$@"
    ;;
esac

#DEBHELPER#

exit 0
