#!/bin/sh -e

upgrade_quirks() {
  [ "$2" ] || return 0

  dpkg --compare-versions $2 lt 1:2.5.1-1.5 || return 0

  # replaced by a symlink in 1:2.5.1-1.3, but dpkg fails to do it on upgrades
  # furthermore the postinst had a bug in 1:2.5.1-1.4 handling wrongly the
  # /usr/share/doc/libatm1-dev directory (it refered to /usr/share/doc/atm-tools
  # previously
  if [ -d /usr/share/doc/libatm1-dev -a ! -L /usr/share/doc/libatm1-dev ] ; then
    rmdir /usr/share/doc/libatm1-dev
    ln -s /usr/share/doc/libatm1 /usr/share/doc/libatm1-dev
  fi

  return 0
}

case "$1" in
    configure)
    upgrade_quirks "$@"
    ;;
esac

#DEBHELPER#

exit 0
